### ISSUE TITLE
KoPeMe File in /tmp Folder

### ISSUE THREAD

**Issue by bam-hbt** [jenkinsci/peass-ci-plugin#230]
### What feature do you want to see added?

Kopeme-xxxx.bin file is created in /tmp folder during the measurement of parametrized test.
Sometimes it does not get deleted, actually should not be located in /tmp Folder.

**Comment by DaGeRe** [comment]
Thanks for the issue, this has been fixed with https://github.com/DaGeRe/KoPeMe/commit/ea10d3840d81de12375fcec7e4abdc86c08aae90. Could you check this fix? If it works, I'll create a release.

**Comment by bam-hbt** [comment]
Thanks for fix, looks fine. Now the created Kopeme files under /tmp folder will be deleted

**Comment by bam-hbt** [comment]
I have to reopen the problem, because the kopeme files still exist in /tmp after multiple tests

**Comment by bam-hbt** [comment]
It's working now!
